# Demo user and password used for Grafana and Influxdb
demo_username: 'demouser'
demo_password: 'demopassword'

# InfluxDB configuration variables
influxdb_username: '{{ demo_username }}'
influxdb_password: '{{ demo_password }}'
influxdb_org: 'demo_org'
influxdb_bucket: 'demobucket'
influxdb_admin_token: 'ZJefZivNGKcY_C5glO_D07_kbrEzBFtYVWemw0ckG9nFZhw5-yWqvX23A5xSzLV1Z93uRp4FUFweaPUlKyTVvw=='
