- name: Create 'influxdb2/data' folder if not exists
  ansible.builtin.file:
    path: '{{ influxdb2_data_path }}'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Create 'influxdb2/config' folder if not exists
  ansible.builtin.file:
    path: '{{ influxdb2_config_path }}'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Create 'influxdb2/tasks' folder if not exists
  ansible.builtin.file:
    path: '{{ influxdb2_tasks_path }}'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Create 'telegraf' folder if not exists
  ansible.builtin.file:
    path: '{{ telegraf_config_path }}'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Create 'grafana/provisioning/datasources' folder if not exists
  ansible.builtin.file:
    path: '{{ grafana_datasources_path }}'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Create 'grafana/provisioning/dashboards' folder if not exists
  ansible.builtin.file:
    path: '{{ grafana_dashboards_path }}'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Create 'portainer_ce/data' folder if not exists
  ansible.builtin.file:
    path: '{{ portainer_ce_data_path }}'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'
