---
# defaults file for indaco.influxdb2

homefolder_path: '/home/{{ ansible_user }}'

influxdb2_data_path: '{{ homefolder_path }}/docker/influxdb2/data'
influxdb2_config_path: '{{ homefolder_path }}/docker/influxdb2/config'
influxdb2_tasks_path: '{{ homefolder_path }}/docker/influxdb2/tasks'
