galaxy_info:
  author: indaco
  description: Update and upgrade the packages on the target system using APT
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - focal
